twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig' ]
    globals:
        identity_service: '@App\Repository\IdentityRepository'
#        post_service: '@App\Repository\PostRepository'
