index:
    path: /
    controller: App\Controller\DefaultController::index

mentions_legales:
    path:         /mentions_legales
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/mentionslegales.html.twig

politique_confidentalite:
    path:         /politique_confidentalite
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/politiqueconfidentialite.html.twig