<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQmeeZQQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQmeeZQQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQmeeZQQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQmeeZQQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQmeeZQQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'QmeeZQQ',
    'container.build_id' => '6d39c47f',
    'container.build_time' => 1608112211,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQmeeZQQ');
