<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFwPUVSH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFwPUVSH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFwPUVSH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFwPUVSH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFwPUVSH\App_KernelDevDebugContainer([
    'container.build_hash' => 'FwPUVSH',
    'container.build_id' => '60ac724a',
    'container.build_time' => 1608134573,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFwPUVSH');
